server:
    port: 15000
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    application:
        name: third-party
    config:
        import:
          - optional:nacos:gulimall.yaml
          - optional:nacos:third-party-dev.yaml
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
                username: nacos
                password: nacos
            config:
                server-addr: localhost:8848
                namespace: 788dc2fc-6986-4479-8534-9f9e875dd426
                username: nacos
                password: nacos

