server:
  port: 12000

spring:
  application:
    name: guli-search
  config:
    import:
      - optional:nacos:gulimall.yaml
      - optional:nacos:guli-search-dev.yaml

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  session:
    store-type: redis

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: 788dc2fc-6986-4479-8534-9f9e875dd426
        username: nacos
        password: nacos
